version: '3.8'

services:
  account-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iae_account_service
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html